#!/bin/bash
# Daily P&L Report — runs at 23:00 UTC via cron
cd /home/ubuntu/clawd

python3 << 'PYEOF'
import json, datetime, os, requests

now = datetime.datetime.now(datetime.timezone.utc)
date_str = now.strftime("%Y-%m-%d")

# Load dashboard data for today's numbers
with open("/home/ubuntu/clawd/dashboard/data.json") as f:
    data = json.load(f)

# HL status
try:
    hl_resp = os.popen("cd /home/ubuntu/clawd/brainKID/trading && node hl.js status 2>/dev/null").read()
except:
    hl_resp = "unavailable"

# PM trade count today
try:
    trades_today = os.popen(f"grep '{date_str}.*TRADE EXECUTED' /home/ubuntu/clawd/polymarket-assistant/trading.log 2>/dev/null | wc -l").read().strip()
except:
    trades_today = "?"

# Outcomes
try:
    outcomes = os.popen(f"grep '{date_str}' /home/ubuntu/clawd/polymarket-assistant/confidence_outcomes.jsonl 2>/dev/null").read()
    wins = outcomes.count('"won": true')
    losses = outcomes.count('"won": false')
except:
    wins = losses = 0

report = f"""# Daily P&L Report — {date_str}

## Summary
- **PM Balance:** ${data['pm_balance']:.2f}
- **HL Balance:** ${data['hl_balance']:.2f}
- **Combined:** ${data['pm_balance'] + data['hl_balance']:.2f}
- **Today P&L:** ${data['today_pnl']:+.2f}
- **All-Time P&L:** ${data['all_time_pnl']:+.2f}

## Trading Activity
- PM trades today: {trades_today}
- Outcomes: {wins}W / {losses}L
- Win rate: {wins/(wins+losses)*100:.0f}% (today)

## HL Positions
{hl_resp}

## Notes
- Auto-generated by daily-pnl-report.sh
"""

report_path = f"/home/ubuntu/clawd/reports/daily-pnl-{date_str}.md"
with open(report_path, 'w') as f:
    f.write(report)
print(f"Report saved: {report_path}")
PYEOF
